[tool.poetry]
name = "booking-challenge-2021"
version = "0.1.0"
description = ""
authors = ["Huy Dang <quanghuy.dang210@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
setuptools = "^68.2.2"
torch = "^2.1.1"
pandas = "^2.1.3"
scikit-learn = "^1.3.2"
numpy = "^1.26.2"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
